# Render deployment configuration
services:
  # Backend API service
  - type: web
    name: courseai-api
    runtime: node
    repo: https://github.com/rohunvora/courseai
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: courseai-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false # Set in dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_TOKEN
        generateValue: true
      - key: PORT
        value: 3001
    healthCheckPath: /health
    autoDeploy: true # Deploy on every push
    plan: starter # $7/month

  # Frontend static site
  - type: static
    name: courseai-frontend
    repo: https://github.com/rohunvora/courseai
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    envVars:
      - key: VITE_API_URL
        value: https://courseai-api.onrender.com/api
      - key: VITE_ENABLE_PREVIEW_FEATURES
        value: false
    autoDeploy: true

# Database
databases:
  - name: courseai-db
    plan: starter # $7/month
    databaseName: courseai
    user: courseai_user

# Environment groups for shared secrets
envVarGroups:
  - name: courseai-secrets
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false